name: DocC Runner

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# A single job that builds and deploys the DocC documentation
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Select Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1.0"
      - name: Build DocC
        run: |
          swift package resolve;

          xcodebuild docbuild -scheme PKSUI -derivedDataPath /tmp/docbuild -destination 'generic/platform=iOS';

          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/PKSUI.doccarchive \
            --output-path docs \
            --hosting-base-path 'PKSUI';

          echo "<script>window.location.href += \"/documentation/pksui\"</script>" > docs/index.html;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs"
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
